# Generated by Django 4.2.3 on 2023-07-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_item_review_purchased_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='item_pics'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
