# Generated by Django 4.2.3 on 2023-07-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_item_image_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='item_default.jpg', upload_to='item_pics'),
        ),
    ]
