# Generated by Django 4.2.3 on 2023-08-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_item_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expire_date',
            field=models.DateField(blank=True),
        ),
    ]
