# Generated by Django 4.2.3 on 2023-07-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_item_sale_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sale_limit',
            new_name='sales_limit',
        ),
    ]
