# Generated by Django 4.2.3 on 2023-07-10 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_rename_sale_limit_item_sales_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_limit',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
