# Generated by Django 4.2.3 on 2023-07-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_item_rating_count_item_sold_item_total_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=2499),
        ),
    ]
