# Generated by Django 4.2.3 on 2023-07-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_item_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchased',
        ),
    ]
