# Generated by Django 4.2.3 on 2023-07-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_rename_orders_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
