# Generated by Django 4.2.3 on 2023-07-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statud',
            field=models.IntegerField(default=0),
        ),
    ]
