# Generated by Django 4.2.3 on 2023-07-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_order_statud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statud',
            new_name='status',
        ),
    ]
