# Generated by Django 4.2.3 on 2023-07-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_rename_statud_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
