# Generated by Django 4.2.3 on 2023-07-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_remove_item_rating_count_remove_item_total_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
